# Assign Probablitites for independent events so that (1 - sum of probablities of independent events)
# will be the total probablity of correlated events
---
output_file_name: test1.log
activity_time_in_seconds: 60
real_time: true
user_id_prefix: U 
new_user_poll_time: 1
new_user_probablity: 0.5
user_segments: 
  segment1:
    number_of_users: 100
    activity_ticker_in_seconds: 1
    activity_probablity_map:
      DoSomething: 0.5
      NoOp: 0.5
      Exit: 0
    event_probablity_map:
      correlation_matrix:
        events:
          E1:
            E1: 0.2
            E2: 0.1
            E4: 0.2
            E5: 0.5
          E2:
            E2: 0.1
            E4: 0.9
          E3:
            E1: 0.5
            E2: 0.5
          E4:
            E1: 0.5
            E5: 0.5
          E5:
            E3: 1.0	
        seed_events: ['E5']
      independent_events:
        E6: 0.01
        E7: 0.05
        E8: 0.03
        E9: 0.01
        E10: 0.2
    event_attributes: 
      E1: 
        category: ea1
        type: ea2
      E2:
        category: ea3
        type: ea2
      E3:
        category: ea1
        type: ea4
    user_attributes:
      U1:
        age: u1
        gender: u2
      U2:
        age: u1
        gender: u3
      U3:
        age: u4
        gender: u2
    set_attributes: true 
...