---
number_of_users: 10
activity_time_in_seconds: 60
activity_ticker_in_seconds: 1
activity_probablity_map:
  DoSomething: 0.5
  NoOp: 0.4
  Exit: 0.1
event_probablity_map:
  E1: 0.2
  E2: 0.3
  E3: 0.1
  E4: 0.1
  E5: 0.3
real_time: false
...