# Assign Probablitites for independent events so that (1 - sum of probablities of independent events)
# will be the total probablity of correlated events
---
output_file_name: test1.log
activity_time_in_seconds: 1800
real_time: true
user_id_prefix: U
new_user_poll_time: 5
new_user_probablity: 0.7
per_tick_new_user_seed_count: 10
user_segments: 
  segment1:
    number_of_users: 100
    activity_ticker_in_seconds: 1
    activity_probablity_map:
      DoSomething: 0.3999
      NoOp: 0.6
      Exit: 0.0001
    event_probablity_map:
      correlation_matrix:
        events:
          Home:
            Create_Ad: 0.5
            Performance_History: 0.2
            Payment_History: 0.08
            Activity_History: 0.07
            Add_Payment_Instrument: 0.05
            Contact_Us: 0.05
            Help_Desk: 0.05
          Help_Desk:
            Raise_Complaint: 0.9 
            Logout: 0.1
          Raise_Complaint:
            Logout: 1.0
          Contact_Us:
            Logout: 1.0
          Payment_History:
            Logout: 1.0
          Activity_History:
            Logout: 1.0
          Performance_History:
            Performance_Improvements_Suggestion: 0.7
            Modify_Targetting: 0.1
            Logout: 0.2
          Performance_Improvements_Suggestion:
            Performance_History: 0.5
            Modify_Targetting: 0.5
          Modify_Targetting:
            Performance_Improvements_Suggestion: 0.5
            Logout: 0.5
          Add_Payment_Instrument:
            Logout: 0.5
            Add_Credit_card: 0.5
          Add_Credit_card:
            Logout: 1.0
          Create_Ad:
            Check_Bid_Details: 0.6
            Check_Targetting_Details: 0.2
            Upload_Image: 0.2
          Check_Bid_Details:
            Home: 0.3
            Check_Targetting_Details: 0.7
          Check_Targetting_Details:
            Upload_Image: 0.7
            Change_Presuggested_Targetting: 0.29
            Create_Ad: 0.01
          Change_Presuggested_Targetting:
            Upload_Image: 0.99
            Create_Ad: 0.01
          Upload_Image:
            Create_Ad: 0.01
            Check_Ad_Preview: 0.99
          Check_Ad_Preview:
            Create_Ad: 0.01
            Submit_Ad: 0.99
          Submit_Ad:
            Logout: 0.5
            Create_Ad: 0.5
          Logout:
            Logout: 1.0
        seed_events: ['Home']
        exit_events: ['Logout']
    event_attributes: 
      Home:
        category: PAGE_VIEW
      Help_Desk:
        category: PAGE_VIEW
      Raise_Complaint:
        category: CLICK_BUTTON
      Contact_Us:
        category: PAGE_VIEW
      Payment_History:
        category: PAGE_VIEW
      Activity_History:
        category: PAGE_VIEW
      Performance_History:
        category: PAGE_VIEW
      Performance_Improvements_Suggestion:
        category: PAGE_VIEW
      Modify_Targetting:
        category: CLICK_BUTTON
      Add_Payment_Instrument:
        category: PAGE_VIEW
      Add_Credit_card:
        category: CLICK_BUTTON
      Create_Ad:
        category: PAGE_VIEW
      Check_Bid_Details:
        category: PAGE_VIEW
      Check_Targetting_Details:
        category: PAGE_VIEW
      Change_Presuggested_Targetting:
        category: CLICK_BUTTON
      Upload_Image:
        category: PAGE_VIEW
      Check_Ad_Preview:
        category: PAGE_VIEW
      Submit_Ad:
        category: CLICK_BUTTON
      Logout:
        category: CLICK_BUTTON
    user_attributes:
      U1:
        age: u1
        gender: u2
      U2:
        age: u1
        gender: u3
      U3:
        age: u4
        gender: u2
      U4:
        age: u1
        gender: u2
      U5:
        age: u1
        gender: u3
      U6:
        age: u4
        gender: u2
      U7:
        age: u1
        gender: u2
      U8:
        age: u1
        gender: u3
      U9:
        age: u4
        gender: u2
      U10:
        age: u1
        gender: u2
      U11:
        age: u1
        gender: u3
      U12:
        age: u4
        gender: u2
    set_attributes: true 
...