name: CI
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          ls .
          go get gopkg.in/yaml.v2 
          go get gopkg.in/natefinch/lumberjack.v2
          go build ./datagen/main.go
          go build ./datafeeder/main.go


